### ISSUE TITLE
Red the HowToInstall.txt, still don't get it

### ISSUE THREAD

**Issue by IanBoni** [benjaminpants/Snailax#2]
Can you give a dtailed explanaition on how to actually install it?

I couldn't understand the "Select the original data.win then the modified version, or if you just open the patch with lunar just select the original" part

**Comment by benjaminpants** [comment]
Sorry, that part really needs some work. It was like 3 AM when I initially wrote that file.

**Comment by benjaminpants** [comment]
updated install text, this shouldn't be much of a problem
